import type { Metadata } from "next";
import { IBM_Plex_Mono, Sen } from "next/font/google";

import "./globals.css";
import { ReactQueryProvider } from "#/providers/ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { TooltipProvider } from "@repo/ui/components/tooltip";

const fontSans = Sen({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-sans",
});

const fontMono = IBM_Plex_Mono({
  weight: ["400", "700"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-thin scheme-dark">
      <body className={`${fontSans.variable} ${fontMono.variable} font-sans`}>
        <TooltipProvider>
          <ReactQueryProvider>
            <ReactQueryDevtools />
            {children}
          </ReactQueryProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
